### ISSUE TITLE
Create a proposals section in the bullhorn

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible.im#13]
Based on the community matrix meeting, we thought it would be helpful to have a Proposals section where we highlight the community-topics we are still requesting discussions or voting on. This would help our movement to more async discussions.

**Comment by gundalow** [comment]
Good idea, I'll do this as I'm updating some other bits in that file.

**Comment by cybette** [comment]
Thanks for the suggestion! Implemented in #14. Closing...
